### ISSUE TITLE
Chore to be done after X days seems to not calculate correctly if it was overdue on completion

### ISSUE THREAD

**Issue by Sono-Gomorrha** [bmcclure/ha-chore-helper#36]
## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 3
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 4.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Terminal & SSH (9.8.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 January 2024 at 16:37
-- | --
current_recorder_run | 17 January 2024 at 09:19
estimated_db_size | 7.74 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bmcclure/ha-chore-helper/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have a chore that is to take out the compost bin after 2 days. What I want is that when I take it out today I mark the chore as complete and then HA will show the chore as due 2 days later. Now the chore was due on the 24th January, but I didn't do it. So today on the 25th the day counter is at -1. I completed the chore this afternoon. What happened is that the day counter is now at 1 (-1 + 2 = 1), and the next due date is tomorrow 26th January. 

![SCR-20240125-l7f](https://github.com/bmcclure/ha-chore-helper/assets/46170978/8a74b4b3-2bc2-4060-ade1-204f6fd732cd)

Unless I did not understand the documentation correctly this seems to be a bug.

Chore config:
![image](https://github.com/bmcclure/ha-chore-helper/assets/46170978/c71f269a-de27-4f43-8335-e5707b68e421)
![image](https://github.com/bmcclure/ha-chore-helper/assets/46170978/07e90b46-c16a-4db9-98b8-0e41653d0073)

### Reproduction steps

1. Create a chore equal to what I showed in the screenshots
2. Complete it and then let it become overdue
3. Complete it while it is overdue
4. The next due date will be incorrect

### Debug logs

```Text
I failed to orderly produce these. When setting the logs to debug, I immediately got a 4.6 MB log file with 6.712 lines. When trying to set the default log level for HA to warning and only set debug for chore_helper I don't get any log entries for chore helper at all.
```

**Comment by Sono-Gomorrha** [comment]
I've closed this issue as my HA did bump the timer to the correct value some time after opening the bug report. So maybe I was just too impatient.

**Comment by adbsmith** [comment]
I actually think this should be re-opened. I am getting completely incorrect calculations on my chores after marking them incomplete if they were overdue.
